#!/usr/bin/env python3
"""Generate the disposable Fraktal/AB reference suite (R5 gate tooling).

**This is gate tooling, not the production module library.** It is disposable
in exactly the sense every Phase 0 fixture is: it exists to be downloaded to an
isolated bench, measured, and replaced. Nothing here is authorized to become a
runtime library, and the scope-exclusion test that guards the S16 fixture
guards this one too.

What it is for. R5 asks for "a disposable reference AOI suite" that runs
through the named isolated-hardware path and emits machine-readable results.
S16 proved the Core §6.1 handshake and the §6.2 mode chain on hardware; this
promotes those two AOIs to the binding's **first two reference types** and adds
the one property a single-instance fixture cannot show:

* the **module** reference type is instantiated **twice**, over two independent
  contexts, driven by independent commands; and
* the suite carries an on-controller **cross-talk** counter, so an instance
  that disturbs its sibling is caught by the controller rather than inferred
  from a host-side read.

That second instance is what AB §5.7's argument actually needs. Core is
inheritance-free, so "prove the base once and inherit it" is not available:
§5.7 says base behaviour is proven once against a reference type and
**G-BEGINEND plus G-GENERATED** extend that proof to every other type. An
extension argument that has never been exercised on a second instance is an
assertion. Here it is measured.

The declaration machinery is imported from ``fraktal_ab_s16_fixture`` rather
than copied, so the reference types are generated by the same code that
generated the fixture S16 proved - which is the only reason promoting them to
"reference" means anything.

Every scalar is a ``DINT``, including the booleans, because S12 removed
``TIME``/``TIME32``/``LREAL`` from this baseline and made ``LINT``
transport-only. **No ``BOOL`` member appears in the public context UDT**: that
layout is a recorded S12 hole, not a local decision.

No physical I/O: the embedded ``Discrete_IO`` module is inhibited, task output
updates are disabled, the generator refuses any ``Local:``/``Discrete_IO:``
operand, and the plant is arithmetic on controller tags.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from fraktal_ab_phase0_fixture import replace_once, scalar_tag, sha256
import fraktal_ab_s16_fixture as declaration


SCHEMA = "fraktal.ab.reference-suite"
SCHEMA_VERSION = 1
CONTROLLER = declaration.CONTROLLER
REVISION = declaration.REVISION

PROGRAM = "FRK_RefProgram"
MAIN_ROUTINE = "FRK_RefMain"
TASK = "FRK_RefTask"

CTX_TYPE = "FRK_T_RefCtx"
CTX_A = "FRK_Ref_CtxA"
CTX_B = "FRK_Ref_CtxB"

# The two reference types. Names carry "Ref" rather than a spike number: they
# are the first two entries of the reference set, not S16 artifacts.
MODULE_AOI = "FRK_Ref_Module"
MODE_AOI = "FRK_Ref_Mode"

MODULE_INSTANCE_A = "FRK_Ref_ModuleInstA"
MODULE_INSTANCE_B = "FRK_Ref_ModuleInstB"
MODE_INSTANCE = "FRK_Ref_ModeInst"

TASK_RATE_MS = declaration.TASK_RATE_MS

WRITABLE_INPUTS = (
    "FRK_Ref_CommandA",
    "FRK_Ref_AbortA",
    "FRK_Ref_ModeSelectA",
    "FRK_Ref_HoldA",
    "FRK_Ref_FaultA",
    "FRK_Ref_CommandB",
)

EVIDENCE_TAGS = (
    "FRK_Ref_ScanCount",
    "FRK_Ref_OrderFail",
    "FRK_Ref_LatencyBad",
    "FRK_Ref_CrossTalk",
    "FRK_Ref_ShadowRunB",
)

CTX_MEMBERS = declaration.CTX_MEMBERS


def ctx_data_type() -> str:
    """The reference context UDT: the S12-proved member set, all ``DINT``."""
    members = "\n".join(
        f'<Member Name="{member.name}" DataType="DINT" Dimension="0" '
        f'Radix="Decimal" Hidden="false" ExternalAccess="Read/Write"/>'
        for member in CTX_MEMBERS
    )
    return f"""<DataTypes>
<DataType Name="{CTX_TYPE}" Family="NoFamily" Class="User">
<Members>
{members}
</Members>
</DataType>
</DataTypes>"""


def aoi_definitions() -> str:
    """The two reference types, from the same machinery that generated S16."""
    module = declaration.aoi_definition(
        MODULE_AOI,
        "Reference type 1 (disposable): Core §6.1 handshake over a simulated plant.",
        declaration.ENABLE_PARAMETERS
        + (
            declaration.parameter("Ctx", CTX_TYPE, "InOut"),
            declaration.parameter("Scan", "DINT", "Input", radix="Decimal"),
            declaration.parameter("Hold", "DINT", "Input", radix="Decimal"),
            declaration.parameter("Fault", "DINT", "Input", radix="Decimal"),
        ),
        declaration.axis_logic(),
        ctx_type=CTX_TYPE,
    )
    mode = declaration.aoi_definition(
        MODE_AOI,
        "Reference type 2 (disposable): Core §6.2 AUTO chain and MANUAL behavior.",
        declaration.ENABLE_PARAMETERS
        + (
            declaration.parameter("Ctx", CTX_TYPE, "InOut"),
            declaration.parameter("Scan", "DINT", "Input", radix="Decimal"),
            declaration.parameter("Sel", "DINT", "Input", radix="Decimal"),
            declaration.parameter("Run", "DINT", "Input", radix="Decimal"),
        ),
        declaration.mode_logic(),
        ctx_type=CTX_TYPE,
    )
    return (
        "<AddOnInstructionDefinitions>\n"
        + module
        + "\n"
        + mode
        + "\n</AddOnInstructionDefinitions>"
    )


def ctx_tag(name: str) -> str:
    members = "\n".join(
        f'<DataValueMember Name="{member.name}" DataType="DINT" '
        f'Radix="Decimal" Value="{declaration._initial_value(member.name)}"/>'
        for member in CTX_MEMBERS
    )
    return f"""<Tag Name="{name}" TagType="Base" DataType="{CTX_TYPE}" Constant="false" ExternalAccess="Read/Write">
<Data Format="Decorated">
<Structure DataType="{CTX_TYPE}">
{members}
</Structure>
</Data>
</Tag>"""


def controller_tags() -> str:
    tags = [ctx_tag(CTX_A), ctx_tag(CTX_B)]
    for name in WRITABLE_INPUTS:
        tags.append(scalar_tag(name, "DINT", "Decimal", "0", "Read/Write"))
    for name in EVIDENCE_TAGS:
        tags.append(scalar_tag(name, "DINT", "Decimal", "0", "Read Only"))
    for instance, aoi in (
        (MODULE_INSTANCE_A, MODULE_AOI),
        (MODULE_INSTANCE_B, MODULE_AOI),
        (MODE_INSTANCE, MODE_AOI),
    ):
        tags.append(
            f'<Tag Name="{instance}" TagType="Base" DataType="{aoi}" '
            f'Constant="false" ExternalAccess="None"/>'
        )
    return "<Tags>\n" + "\n".join(tags) + "\n</Tags>"


def main_routine_logic() -> tuple[str, ...]:
    """Both module instances first, unconditionally; sequence intent second.

    The ordering rule S11 proved for §3.5 and S16 restated for §6.1 binds every
    instance, not just the one a chain happens to drive. The mode owner checks
    it for context A; the cross-talk counter checks that instance B was not
    disturbed while it was left alone.
    """
    return (
        "FRK_Ref_ScanCount := FRK_Ref_ScanCount + 1;",
        "",
        "(* Unconditional calls: every module instance runs before any intent *)",
        (
            f"{MODULE_AOI}({MODULE_INSTANCE_A},{CTX_A},FRK_Ref_ScanCount,"
            "FRK_Ref_HoldA,FRK_Ref_FaultA);"
        ),
        (
            f"{MODULE_AOI}({MODULE_INSTANCE_B},{CTX_B},FRK_Ref_ScanCount,0,0);"
        ),
        "",
        "(* Sequence intent, over context A only *)",
        (
            f"{MODE_AOI}({MODE_INSTANCE},{CTX_A},FRK_Ref_ScanCount,"
            "FRK_Ref_ModeSelectA,FRK_Ref_CommandA);"
        ),
        f"{CTX_A}.Abort := FRK_Ref_AbortA;",
        "",
        "(* Instance B is driven directly, so the second instance is independent *)",
        f"{CTX_B}.Execute := FRK_Ref_CommandB;",
        "",
        "(* Cross-talk: B must never start a run it was not commanded to start *)",
        "IF FRK_Ref_CommandB = 0 THEN",
        f"IF {CTX_B}.RunCount <> FRK_Ref_ShadowRunB THEN",
        "FRK_Ref_CrossTalk := FRK_Ref_CrossTalk + 1;",
        "END_IF;",
        "END_IF;",
        f"FRK_Ref_ShadowRunB := {CTX_B}.RunCount;",
        "",
        f"FRK_Ref_OrderFail := {CTX_A}.OrderFail;",
        f"FRK_Ref_LatencyBad := {CTX_A}.LatencyBad;",
    )


def programs() -> str:
    lines = "\n".join(
        f'<Line Number="{index}"><![CDATA[{statement}]]></Line>'
        for index, statement in enumerate(main_routine_logic())
    )
    return f"""<Programs>
<Program Name="{PROGRAM}" TestEdits="false" MainRoutineName="{MAIN_ROUTINE}" Disabled="false" UseAsFolder="false">
<Tags/>
<Routines>
<Routine Name="{MAIN_ROUTINE}" Type="ST">
<STContent>
{lines}
</STContent>
</Routine>
</Routines>
</Program>
</Programs>"""


TASKS = f"""<Tasks>
<Task Name="{TASK}" Type="PERIODIC" Rate="{TASK_RATE_MS}" Watchdog="500" Priority="10" DisableUpdateOutputs="true" InhibitTask="false">
<ScheduledPrograms>
<ScheduledProgram Name="{PROGRAM}"/>
</ScheduledPrograms>
</Task>
</Tasks>"""


# The suite must not grow into the runtime base structure. Same fence as S16.
EXCLUDED_TERMS = (
    "Recipe", "ParCfg", "Manifest", "Registry", "Mailbox",
    "Traceability", "ReleaseReport",
)


def all_generated_logic() -> str:
    return "\n".join(
        list(declaration.axis_logic())
        + list(declaration.mode_logic())
        + list(main_routine_logic())
    )


def generate(source: Path, output: Path) -> dict[str, object]:
    source = source.resolve()
    output = output.resolve()
    if not source.is_file():
        raise ValueError(f"source does not exist: {source}")
    if source.suffix.lower() != ".l5x" or output.suffix.lower() != ".l5x":
        raise ValueError("source and output must use the .L5X extension")
    if source == output:
        raise ValueError("output must differ from source")
    if output.exists():
        raise ValueError(f"refusing to overwrite output: {output}")

    text = source.read_text(encoding="utf-8-sig")
    required = (
        f'ProcessorType="{CONTROLLER}"',
        f'MajorRev="{REVISION}"',
        '<Controller Use="Target" Name="FraktalPhase0"',
        "<DataTypes/>",
        "<AddOnInstructionDefinitions/>",
        "<Tags/>",
        "<Programs/>",
        "<Tasks/>",
    )
    missing = [marker for marker in required if marker not in text]
    if missing:
        raise ValueError(f"source is not the expected empty v33 fixture: {missing}")

    logic = all_generated_logic()
    if re.search(r"\b(?:Local|Discrete_IO):[IOC]", logic):
        raise AssertionError("suite logic contains an I/O operand")
    for forbidden in ("TIME", "TIME32", "LREAL", "LINT"):
        if re.search(rf'DataType="{forbidden}"', ctx_data_type()):
            raise AssertionError(f"context uses a type S12 excluded: {forbidden}")
    if re.search(r'DataType="BOOL"', ctx_data_type()):
        raise AssertionError("public context UDT must not carry a BOOL member")

    text = replace_once(text, "<DataTypes/>", ctx_data_type())
    text = replace_once(text, "<AddOnInstructionDefinitions/>", aoi_definitions())
    text = replace_once(text, "<Tags/>", controller_tags())
    text = replace_once(text, "<Programs/>", programs())
    text = replace_once(text, "<Tasks/>", TASKS)

    text, inhibit_count = re.subn(
        r'(<Module Name="Discrete_IO"[^>]*\bInhibited=")false("[^>]*>)',
        r"\1true\2",
        text,
        count=1,
    )
    if inhibit_count != 1:
        raise ValueError("embedded Discrete_IO module was not inhibited exactly once")

    for term in EXCLUDED_TERMS:
        if term in text:
            raise AssertionError(
                f"reference suite must stay disposable; it grew a {term!r}"
            )

    output.write_text(text, encoding="utf-8", newline="\n")
    return {
        "Schema": SCHEMA,
        "SchemaVersion": SCHEMA_VERSION,
        "Disposable": True,
        "Source": str(source),
        "SourceSha256": sha256(source),
        "Output": str(output),
        "OutputSha256": sha256(output),
        "Controller": CONTROLLER,
        "MajorRevision": int(REVISION),
        "PhysicalIoReferences": 0,
        "EmbeddedIoInhibited": True,
        "TaskOutputUpdatesDisabled": True,
        "ReferenceTypes": [MODULE_AOI, MODE_AOI],
        "AoiDefinitions": 2,
        "ModuleInstances": 2,
        "Contexts": [CTX_A, CTX_B],
        "ContextMembers": len(CTX_MEMBERS),
        "BoolMembersInPublicUdt": 0,
        "TaskRateMs": TASK_RATE_MS,
        "WritableInputs": list(WRITABLE_INPUTS),
        "EvidenceTags": list(EVIDENCE_TAGS),
        "Programs": 1,
        "Routines": 1,
        "Tasks": 1,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        evidence = generate(args.source, args.output)
    except (OSError, ValueError, AssertionError) as exc:
        print(f"ERROR [reference-suite] {exc}", file=sys.stderr)
        return 2
    print(json.dumps(evidence, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
