name: fraktal_gateway
description: Fraktal browser WebSocket to native OPC UA gateway service.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fraktal_opcua_client:
    path: ../packages/fraktal_opcua_client
