// GENERATED FILE — DO NOT EDIT.
// Source: PLC E_Reason + registered PL_*Reasons constants.

library;

const generatedReasonEnglish = <String, String>{
  "std.reason.10": "Task overrun.",
  "std.reason.11": "Task jitter high.",
  "std.reason.12": "CPU load high.",
  "std.reason.13": "Memory low.",
  "std.reason.14": "IPC temp high.",
  "std.reason.15": "Fieldbus master fault.",
  "std.reason.16": "DC sync lost.",
  "std.reason.17": "Time sync lost.",
  "std.reason.18": "Utility deviation.",
  "std.reason.19": "IPC fan fault.",
  "std.reason.20": "Storage health low.",
  "std.reason.21": "Controller metrics unavailable.",
  "std.reason.2001": "Timeout.",
  "std.reason.2002": "Permissive not met.",
  "std.reason.2003": "Interlock dropped.",
  "std.reason.2004": "Recipe invalid.",
  "std.reason.2005": "Step stalled.",
  "std.reason.2006": "Retry exhausted.",
  "std.reason.2007": "Cycle time degraded.",
  "std.reason.2008": "Unsupported command.",
  "std.reason.2010": "Link timeout.",
  "std.reason.2011": "Device not ready.",
  "std.reason.2012": "Device protocol error.",
  "std.reason.2020": "Carrier read failed.",
  "std.reason.2021": "Carrier write failed.",
  "std.reason.2022": "Part id mismatch.",
  "std.reason.2023": "Result record rejected.",
  "std.reason.2024": "Part received.",
  "std.reason.2025": "Part processing started.",
  "std.reason.2026": "Part processed.",
  "std.reason.2027": "Part processing aborted.",
  "std.reason.10101": "Cylinder not extended.",
  "std.reason.10102": "Cylinder not retracted.",
  "std.reason.10103": "Cylinder both sensors.",
  "std.reason.10111": "Cylinder home not reached.",
  "std.reason.10112": "Cylinder work not reached.",
  "std.reason.10113": "Cylinder position implausible.",
  "std.reason.10114": "Cylinder sensor lost.",
  "std.reason.10115": "Cylinder configuration invalid.",
  "std.reason.10116": "Cylinder discrepancy.",
  "std.reason.10401": "Device channel fault.",
  "std.reason.10402": "Device response timeout.",
  "std.reason.10403": "Device protocol.",
  "std.reason.10404": "Device not connected.",
  "std.reason.10405": "Device configuration invalid.",
  "std.reason.10406": "Device receive overflow.",
  "std.reason.10501": "Power enable withheld.",
  "std.reason.10502": "Power feedback timeout.",
  "std.reason.10601": "Air switch conflict.",
  "std.reason.11001": "Clamp not confirmed.",
};

const generatedReasonSymbolByCode = <int, String>{
  10: "TASK_OVERRUN",
  11: "TASK_JITTER_HIGH",
  12: "CPU_LOAD_HIGH",
  13: "MEMORY_LOW",
  14: "IPC_TEMP_HIGH",
  15: "FIELDBUS_MASTER_FAULT",
  16: "DC_SYNC_LOST",
  17: "TIME_SYNC_LOST",
  18: "UTILITY_DEVIATION",
  19: "IPC_FAN_FAULT",
  20: "STORAGE_HEALTH_LOW",
  21: "CONTROLLER_METRICS_UNAVAILABLE",
  2001: "TIMEOUT",
  2002: "PERMISSIVE_NOT_MET",
  2003: "INTERLOCK_DROPPED",
  2004: "RECIPE_INVALID",
  2005: "STEP_STALLED",
  2006: "RETRY_EXHAUSTED",
  2007: "CYCLE_TIME_DEGRADED",
  2008: "UNSUPPORTED_COMMAND",
  2010: "LINK_TIMEOUT",
  2011: "DEVICE_NOT_READY",
  2012: "DEVICE_PROTOCOL_ERROR",
  2020: "CARRIER_READ_FAILED",
  2021: "CARRIER_WRITE_FAILED",
  2022: "PART_ID_MISMATCH",
  2023: "RESULT_RECORD_REJECTED",
  2024: "EVENT_PART_RECEIVED",
  2025: "EVENT_PART_PROCESSING_STARTED",
  2026: "EVENT_PART_PROCESSED",
  2027: "EVENT_PART_PROCESSING_ABORTED",
  10101: "CYL_NOT_EXTENDED",
  10102: "CYL_NOT_RETRACTED",
  10103: "CYL_BOTH_SENSORS",
  10111: "CYL_HOME_NOT_REACHED",
  10112: "CYL_WORK_NOT_REACHED",
  10113: "CYL_POS_IMPLAUSIBLE",
  10114: "CYL_SENSOR_LOST",
  10115: "CYL_CFG_INVALID",
  10116: "CYL_DISCREPANCY",
  10401: "DEV_CHANNEL_FAULT",
  10402: "DEV_RESP_TIMEOUT",
  10403: "DEV_PROTOCOL",
  10404: "DEV_NOT_CONNECTED",
  10405: "DEV_CFG_INVALID",
  10406: "DEV_RX_OVERFLOW",
  10501: "POWER_ENABLE_WITHHELD",
  10502: "POWER_FEEDBACK_TIMEOUT",
  10601: "AIR_SWITCH_CONFLICT",
  11001: "CLAMP_NOT_CONFIRMED",
};

String reasonDescriptionKey(int reasonCode, String fallback) =>
    reasonCode != 0 && generatedReasonSymbolByCode.containsKey(reasonCode)
        ? 'std.reason.$reasonCode'
        : fallback;
